hermine/cube/urls.py
# SPDX-FileCopyrightText: 2021 Hermine-team <hermine@inno3.fr>
# SPDX-FileCopyrightText: 2022 Martin Delabre <gitlab.com/delabre.martin>
#
# SPDX-License-Identifier: AGPL-3.0-only
from django.urls import path, include
from rest_framework.authtoken import views as authviews
from rest_framework_nested import routers

from . import views, api_views

app_name = "cube"
urlpatterns = [
    path("", views.IndexView.as_view(), name="root"),
    path("about/", views.AboutView.as_view(), name="about"),
    # Product views
    path("products/", views.ProductListView.as_view(), name="products"),
    path("product/<int:pk>/", views.ProductDetailView.as_view(), name="product_detail"),
    path(
        "product/<int:product_pk>/add_release/",
        views.ProductAddReleaseView.as_view(),
        name="product_add_release",
    ),
    path("product/add/", views.ProductAddView.as_view(), name="product_add"),
    path(
        "product/edit/<int:pk>/", views.ProductEditView.as_view(), name="product_edit"
    ),
    # Product categories views
    path("categories/", views.CategoryListView.as_view(), name="categories"),
    path(
        "category/<int:pk>/", views.CategoryDetailView.as_view(), name="category_detail"
    ),
    path("category/add/", views.CategoryAddView.as_view(), name="category_add"),
    path(
        "category/edit/<int:pk>/",
        views.CategoryEditView.as_view(),
        name="category_edit",
    ),
    # Components views
    path("components/", views.ComponentListView.as_view(), name="components"),
    path("components/popular/", views.PopularListView.as_view(), name="populars"),
    path("component/<int:pk>/", views.ComponentView.as_view(), name="component_detail"),
    path(
        "component/<int:component_id>/update_funding/",
        views.component_update_funding,
        name="component_update_funding",
    ),
    path(
        "licensecurations/",
        views.LicenseCurationListView.as_view(),
        name="licensecurations",
    ),
    path(
        "licensecurations/add/",
        views.LicenseCurationCreateView.as_view(),
        name="licensecuration_create",
    ),
    path(
        "licensecurations/update/<int:pk>/",
        views.LicenseCurationUpdateView.as_view(),
        name="licensecuration_update",
    ),
    path(
        "licensecurations/export/",
        views.ExportLicenseCurationsView.as_view(),
        name="licensecurations_export",
    ),
    path(
        "licensecurations/<int:pk>/export/",
        views.ExportSingleLicenseCurationView.as_view(),
        name="licensecuration_export",
    ),
    # Licenses and policy views
    path("licenses/", views.LicensesListView.as_view(), name="licenses"),
    path("license/<int:pk>/", views.LicenseDetailView.as_view(), name="license"),
    path(
        "license/<int:pk>/edit/", views.LicenseUpdateView.as_view(), name="license_edit"
    ),
    path("license/add/", views.LicenseAddView.as_view(), name="license_add"),
    path(
        "license/<int:license_id>/export/",
        views.Export1LicenseView.as_view(),
        name="export_license",
    ),
    path(
        "license/<int:pk>/print/",
        views.PrintLicense.as_view(),
        name="print_license",
    ),
    path(
        "license/<int:license_pk>/add_obligation/",
        views.ObligationCreateView.as_view(),
        name="obligation_create",
    ),
    path(
        "obligation/<int:pk>/edit/",
        views.ObligationUpdateView.as_view(),
        name="obligation_edit",
    ),
    path(
        "obligation/<int:pk>/delete/",
        views.ObligationDeleteView.as_view(),
        name="obligation_delete",
    ),
    path("generics/", views.GenericListView.as_view(), name="generics"),
    path("generic/<int:pk>/", views.GenericDetailView.as_view(), name="generic"),
    path(
        "export/licenses/", views.ExportLicensesView.as_view(), name="export_licenses"
    ),
    path(
        "export/generics/", views.ExportGenericsView.as_view(), name="export_generics"
    ),
    # License policy views
    path(
        "license/<int:license_pk>/add_autorized_context/",
        views.AuthorizedContextCreateView.as_view(),
        name="authorized_context_create",
    ),
    path(
        "authorized_context/<int:pk>/edit/",
        views.AuthorizedContextUpdateView.as_view(),
        name="authorized_context_edit",
    ),
    path(
        "authorized_context/",
        views.AuthorizedContextListView.as_view(),
        name="authorized_context_list",
    ),
    path(
        "derogations/",
        views.DerogationListView.as_view(),
        name="derogations",
    ),
    path(
        "licensechoices/", views.LicenseChoiceListView.as_view(), name="licensechoices"
    ),
    # Releases views
    path(
        "release/<int:pk>/edit/",
        views.ReleaseUpdateView.as_view(),
        name="release_edit",
    ),
    path(
        "release/<int:release_pk>/",
        views.ReleaseSummaryView.as_view(),
        name="release_summary",
    ),
    path(
        "release/<int:pk>/import/",
        views.ReleaseImportView.as_view(),
        name="release_import",
    ),
    path(
        "release/<int:pk>/bom/export/",
        views.ReleaseBomExportView.as_view(),
        name="release_bom_export",
    ),
    path(
        "release/<int:release_pk>/bom/",
        views.ReleaseSBOMView.as_view(),
        name="release_bom",
    ),
    path(
        "release/<int:pk>/obligations/",
        views.ReleaseObligView.as_view(),
        name="release_oblig",
    ),
    path(
        "release/<int:release_pk>/obligations/<int:generic_id>/",
        views.ReleaseGenericView.as_view(),
        name="release_generic",
    ),
    # Release validation related views
    path(
        "release/<int:pk>/validation/",
        views.ReleaseValidationView.as_view(),
        name="release_validation",
    ),
    ## Step 1
    path(
        "usage/<int:usage_pk>/add_license_curation/",
        views.ReleaseLicenseCurationCreateView.as_view(),
        name="release_licensecuration_create",
    ),
    path(
        "release/<int:id>/validation/fixed_licenses/",
        views.ReleaseCuratedLicensesListView.as_view(),
        name="release_curated_licenses",
    ),
    path(
        "usage/<int:pk>/update_license_curation/",
        views.UpdateLicenseCurationView.as_view(),
        name="release_update_license_curation",
    ),
    ### Step 2
    path(
        "usage/<int:usage_pk>/add_ands_validation/",
        views.ReleaseAndsValidationCreateView.as_view(),
        name="release_andsvalidation_create",
    ),
    path(
        "release/<int:id>/validation/ands_validations/",
        views.ReleaseAndsValidationListView.as_view(),
        name="release_ands_validations",
    ),
    path(
        "usage/<int:pk>/update_ands_validation/",
        views.UpdateAndsValidationView.as_view(),
        name="release_update_andsvalidation",
    ),
    ### Step 3
    path(
        "release/<int:release_pk>/add_exploitation/",
        views.ReleaseExploitationCreateView.as_view(),
        name="release_exploitation_create",
    ),
    path(
        "release/<int:release_pk>/exploitations/",
        views.ReleaseExploitationsListView.as_view(),
        name="release_exploitations",
    ),
    path(
        "release/<int:release_pk>/edit_exploitation/<int:pk>/",
        views.ReleaseExploitationUpdateView.as_view(),
        name="release_edit_exploitation",
    ),
    path(
        "release/<int:release_pk>/delete_exploitation/<int:pk>/",
        views.ReleaseExploitationDeleteView.as_view(),
        name="release_delete_exploitation",
    ),
    ## Step 4
    path(
        "usage/<int:usage_pk>/add_license_choice/",
        views.ReleaseLicenseChoiceCreateView.as_view(),
        name="release_licensechoice_create",
    ),
    path(
        "release/<int:id>/validation/license_choices/",
        views.ReleaseLicenseChoiceListView.as_view(),
        name="release_license_choices",
    ),
    path(
        "release/update_license_choice/<int:pk>/",
        views.UpdateLicenseChoiceView.as_view(),
        name="release_update_license_choice",
    ),
    ## Step 5
    path(
        "usage/<int:usage_pk>/add_derogation/<int:license_pk>/",
        views.ReleaseDerogationCreateView.as_view(),
        name="release_derogation_create",
    ),
    # TODO move this in API urls
    path(
        "api/usagesflat/",
        api_views.UsageFlatList.as_view(),
        name="api_usagesflat",
    ),
    path("api/token-auth/", authviews.obtain_auth_token),
]

# API urls


class Router(routers.DefaultRouter):
    APIRootView = api_views.RootView


router = Router()

# Validation pipeline endpoints
router.register(r"upload_spdx", api_views.UploadSPDXViewSet, basename="upload_spdx")
router.register(r"upload_ort", api_views.UploadORTViewSet, basename="upload_ort")
router.register(r"releases", api_views.ReleaseViewSet, basename="releases")

# Generic obligations
router.register(r"generics", api_views.GenericViewSet, basename="generics")

# Models CRUD viewsets
router.register(r"obligations", api_views.ObligationViewSet, basename="obligations")
router.register(r"components", api_views.ComponentViewSet, basename="components")
router.register(r"usages", api_views.UsageViewSet, basename="usages")
router.register(r"products", api_views.ProductViewSet, basename="products")
router.register(r"licenses", api_views.LicenseViewSet, basename="licenses")
router.register(r"curations", api_views.LicenseCurationViewSet, basename="curations")
router.register(r"choices", api_views.LicenseChoiceViewSet, basename="choices")
router.register(r"derogations", api_views.DerogationViewSet, basename="derogations")

obligation_router = routers.NestedSimpleRouter(router, r"licenses")
obligation_router.register(
    r"obligations",
    api_views.ObligationViewSet,
    basename="license-obligations",
)

product_router = routers.NestedSimpleRouter(router, r"products")
product_router.register(
    r"releases", api_views.ReleaseViewSet, basename="product-releases"
)

hermine/hermine/urls.py
# SPDX-FileCopyrightText: 2021 Hermine-team <hermine@inno3.fr>
# SPDX-FileCopyrightText: 2022 Martin Delabre <gitlab.com/delabre.martin>
#
# SPDX-License-Identifier: AGPL-3.0-only

"""hermine URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.db import connection, Error as DBError, OperationalError
from django.http import HttpResponse, HttpResponseServerError
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Hermine API",
        default_version="v1",
        description="Hermine Rest API documentation",
        # terms_of_service="https://hermine-foss.org/",
        contact=openapi.Contact(email="hermine@inno3.fr"),
        license=openapi.License(name="AGPL-3.0-only"),
    ),
    public=False,
    permission_classes=[
        permissions.IsAuthenticated,
    ],
)


def ready(r):
    try:
        with connection.cursor() as cursor:
            cursor.execute("SELECT 1;")
            row = cursor.fetchone()
            if row is None:
                return HttpResponseServerError("Database: invalid response")
    except DBError:
        return HttpResponseServerError("Database: cannot connect")

    return HttpResponse("OK")


urlpatterns = [
    path("", include("cube.urls")),
    path("ping/", lambda r: HttpResponse("OK")),
    path("ready/", ready),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("oauth/", include("social_django.urls", namespace="social")),
    re_path(
        r"^api-doc(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^api-doc-swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    re_path(
        r"^api-doc/$",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

hermine/cube/models/products.py
#  SPDX-FileCopyrightText: 2021 Hermine-team <hermine@inno3.fr>
#
#  SPDX-License-Identifier: AGPL-3.0-only

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse_lazy


class Product(models.Model):
    """
    A product which dependencies are to be audited.
    """

    name = models.CharField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    categories = models.ManyToManyField(
        "Category", db_table="cube_category_products", blank=True
    )

    def get_absolute_url(self):
        return reverse_lazy("cube:product_detail", args=[self.id])

    def __str__(self):
        return self.name


class Category(models.Model):
    """
    A category of product
    """

    name = models.CharField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def get_absolute_url(self):
        return reverse_lazy("cube:category_detail", args=[self.id])

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Product category"
        verbose_name_plural = "Product categories"


class Release(models.Model):
    """
    A specific release of a product
    """

    SHIPPING_CHOICES = [
        ("Archived", "Archived"),
        ("Active", "In developpement"),
        ("Published", "Published"),
    ]
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="releases"
    )
    release_number = models.CharField(max_length=200)
    ship_status = models.CharField(max_length=20, choices=SHIPPING_CHOICES, blank=True)
    pub_date = models.DateTimeField("date published", blank=True, null=True)
    # Last completed step, 0 when none is validated
    valid_step = models.IntegerField("Validation Step", blank=True, null=True)
    commit = models.CharField("Commit hash or ref", max_length=255, blank=True)

    def get_absolute_url(self):
        return reverse_lazy("cube:release_summary", args=[self.id])

    def __str__(self):
        return self.product.__str__() + " " + self.release_number

    class Meta:
        unique_together = ["product", "release_number"]
        verbose_name = "Product release"
        verbose_name_plural = "Product releases"


class Exploitation(models.Model):
    """
    Stores how a release is exploited (so all its Usage can be updated accordingly)
    """

    from cube.models.components import Usage

    release = models.ForeignKey(
        Release, on_delete=models.CASCADE, related_name="exploitations"
    )
    scope = models.CharField(
        max_length=50, blank=True, help_text="Leave blank to apply for any scope"
    )
    project = models.CharField(
        max_length=750, blank=True, help_text="Leave blank to apply for any project"
    )
    exploitation = models.CharField(
        max_length=50,
        choices=Usage.EXPLOITATION_CHOICES,
        default=Usage.EXPLOITATION_DISTRIBUTION_BOTH,
    )

    def __str__(self):
        return self.release.__str__() + " : " + str(self.scope)

    class Meta:
        unique_together = ["release", "scope", "project"]

hermine/cube/views/misc.py
#  SPDX-FileCopyrightText: 2021 Hermine-team <hermine@inno3.fr>
#  SPDX-FileCopyrightText: 2022 Martin Delabre <gitlab.com/delabre.martin>
#
#  SPDX-License-Identifier: AGPL-3.0-only

#
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.shortcuts import render
from django.views.generic import TemplateView

from cube.models import License, Product, Component, Release, Generic


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = "cube/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context["latest_license_list"] = License.objects.filter(
            status="Tocheck"
        ).annotate(Count("obligation"))
        context["nb_products"] = Product.objects.all().count()
        context["nb_releases"] = Release.objects.all().count()
        context["nb_components"] = Component.objects.all().count()
        context["nb_licenses"] = License.objects.all().count()
        context["nb_generics"] = Generic.objects.all().count()
        kwargs.update(context)

        return kwargs


class AboutView(LoginRequiredMixin, TemplateView):
    template_name = "cube/about.html"


def about(request):
    context = {}
    return render(request, "cube/about.html", context)

hermine/cube/templates/cube/authorized_context_list.html
<!--
SPDX-FileCopyrightText: 2021 Hermine-team <hermine@inno3.fr>

SPDX-License-Identifier: AGPL-3.0-only
-->

{% extends "cube/cube.html" %}
{% load cube_tags %}
{% block title %}Authorized context{% endblock %}
{% block breadcrumbs %}
<ul>
  <li>Hermine</li>
  <li><a href="{% url 'cube:licenses' %}">Licenses</a></li>
  <li>Authorized contexts</li>
</ul>
{% endblock %}
{% block herozone %}
<h1 class="title">
  <span class="icon is-medium"><i class="fas fa-clipboard-check"></i></span>
Authorized contexts
</h1>
{% endblock %}
{% block content %}
<div id="content-main">
  <p>Authorized contexts allow use of a restricted licence for any all products or a category of products.</p>
  <table class="table is-striped is-hoverable">
    <thead>
      <tr>
        <th>License</th>
        <th>Product category</th>
        <th>Component / Version</th>
        <th>Scope</th>
        <th>Linking</th>
        <th>Modification</th>
        <th>Exploitation</th>
        <th>Justification</th>
        <th>Updated</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
  {% for derogation in authorized_contexts %}
      <tr>
        <td>
          <a href="{% url 'cube:license' derogation.license.id %}"><span class="tag {{ derogation.license|licenseAllowedCSS }}">
          {{ derogation.license.spdx_id }}
          </span></a>
        </td>
        <td>{{ derogation.category|default:"<em>Any</em>" }}</td>
        <td>{{ derogation.version|default:derogation.component|default:"<em>Any</em>" }}</td>
        <td>{{ derogation.scope|default:"<em>Any</em>" }}</td>
        <td>{{ derogation.get_linking_display|default:"<em>Any</em>" }}</td>
        <td>{{ derogation.get_modification_display|default:"<em>Any</em>" }}</td>
        <td>{{ derogation.get_exploitation_display|default:"<em>Any</em>" }}</td>
        <td>{{ derogation.justification|default:"<em>No justification</em>"|truncatewords:13 }}</td>
        <td>{{ derogation.updated }} ({{ derogation.author|default:"<em>author unknown</em>" }})</td>
        <td style="white-space: nowrap">
          <a href="{% url "cube:authorized_context_edit" derogation.id %}"><span class="icon"><i class="fas fa-edit"></i></span></a> |
          <a href="{% url "admin:cube_derogation_delete" derogation.id %}"><span class="icon"><i class="fas fa-trash"></i></span></a>
        </td>
  {% endfor %}
  </tbody>
</table>
</div>

{% endblock %}

hermine/cube/templates/cube/cube.html
<!--
SPDX-FileCopyrightText: Viktor Kuzhelny https://github.com/vikdiesel/admin-one-bulma-dashboard/
SPDX-FileCopyrightText: 2021 Hermine-team <hermine@inno3.fr>
SPDX-FileCopyrightText: 2022 Martin Delabre <gitlab.com/delabre.martin>
SPDX-License-Identifier: MIT
-->
<!DOCTYPE html>
<html lang="en" class="has-aside-left has-aside-mobile-transition has-navbar-fixed-top has-aside-expanded">
  <head>
    {% load static %}
    <link rel="preload" href="{% static 'cube/css/main.min.css' %}" as="style">
    <link rel="stylesheet" type="text/css" href="{% static 'cube/css/main.min.css' %}">
    <link rel="preload" href="{% static 'cube/css/fontawesome-free-all.css' %}" as="style">
    <link rel="stylesheet" type="text/css" href="{% static 'cube/css/fontawesome-free-all.css' %}">
    <!-- Fonts -->
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet" type="text/css">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <title>{% block title %}{% endblock %} - Hermine
    </title>
  </head>
  <body>
    <div id="app">
      <nav id="navbar-main" class="navbar is-fixed-top">
        <div class="navbar-brand">
          <a class="navbar-item is-hidden-desktop jb-aside-mobile-toggle">
            <span class="icon">
              <i class="fas fa-bars">
              </i>
            </span>
          </a>
        </div>
        <div class="navbar-brand is-right">
          <a class="navbar-item is-hidden-desktop jb-navbar-menu-toggle" data-target="navbar-menu">
            <span class="icon"><i class="fas fa-ellipsis-v"></i></span>
          </a>
        </div>
        <div class="navbar-menu fadeIn animated faster" id="navbar-menu">
          <div class="navbar-end">
            <a class="navbar-item" href="{% url 'admin:auth_user_change' user.id %}">
              <div class="is-user-avatar">
                <span class="icon"><i class="fas fa-user"></i></span>
              </div>
              <div class="is-user-name">
                <span>{%if user.first_name or user.last_name %}{{user.first_name}} {{user.last_name}}{%else%}{{user.username}}{%endif%}
                </span>
              </div>
            </a>
            <a title="Log out" class="navbar-item is-desktop-icon-only" href="{% url 'logout' %}">
              <span class="icon"><i class="fas fa-sign-out-alt"></i></span>
              <span>Log out</span>
            </a>
          </div>
        </div>
      </nav>
      <aside class="aside is-placed-left is-expanded">
        <div class="aside-tools">
          <div class="aside-tools-label">
            <span><b>Hermine</b></span>
          </div>
        </div>
        <div class="menu is-menu-main">
          <p class="menu-label">General</p>
          <ul class="menu-list">
            <li>
              <a href="/" class="has-icon">
                <span class="icon"><i class="fas fa-chart-pie"></i></span>
                <span class="menu-item-label">Dashboard</span>
              </a>
            </li>
          </ul>
          <p class="menu-label">Development</p>
          <ul class="menu-list">
            <li>
              <a class="has-icon has-dropdown-icon">
                <span class="icon"><i class="fas fa-cubes"></i></span>
                <span class="menu-item-label">Your products</span>
                <div class="dropdown-icon">
                  <span class="icon"><i class="fas fa-caret-right"></i></span>
                </div>
              </a>
              <ul>
                <li>
                  <a href="{% url 'cube:products' %}">
                    <span>All products</span>
                  </a>
                </li>
                <li>
                  <a href="{% url 'cube:categories' %}">
                    <span>Product categories</span>
                  </a>
                </li>
              </ul>
            </li>

            <li>
              <a class="has-icon has-dropdown-icon">
                <span class="icon"><i class="fas fa-puzzle-piece"></i></span>
                <span class="menu-item-label">Components</span>
                <div class="dropdown-icon">
                  <span class="icon"><i class="fas fa-caret-right"></i></span>
                </div>
              </a>
              <ul>
                <li>
                  <a href="{% url 'cube:components' %}">
                    <span>Complete List</span>
                  </a>
                </li>
                <li>
                  <a href="{% url 'cube:populars' %}">
                    <span>Most used ones</span>
                  </a>
                </li>
                <li>
                  <a href="{% url 'cube:licensecurations' %}">
                    <span>Curations</span>
                  </a>
                </li>
              </ul>
            </li>
          </ul>
          <p class="menu-label">Legal
          </p>
          <ul class="menu-list">
            <li>
              <a href="{% url 'cube:licenses' %}" class="has-icon">
                <span class="icon">
                  <i class="fas fa-balance-scale">
                  </i>
                </span>
                <span class="menu-item-label">Licenses
                </span>
              </a>
            </li>
            <li>
              <a href="{% url 'cube:generics' %}" class=" has-icon">
                <span class="icon">
                  <i class="fas fa-award">
                  </i>
                </span>
                <span class="menu-item-label">Generic obligations
                </span>
              </a>
            </li>
            <li>
              <a href="{% url 'cube:authorized_context_list' %}" class=" has-icon">
                <span class="icon">
                  <i class="fas fa-clipboard-check">
                  </i>
                </span>
                <span class="menu-item-label">Authorized contexts
                </span>
              </a>
            </li>
            <li>
              <a href="{% url 'cube:derogations' %}" class=" has-icon">
                <span class="icon">
                  <i class="fas fa-clipboard-check">
                  </i>
                </span>
                <span class="menu-item-label">Derogations
                </span>
              </a>
            </li>
            <li>
              <a href="{% url 'cube:licensechoices' %}" class=" has-icon">
                <span class="icon">
                  <i class="fas fa-project-diagram">
                  </i>
                </span>
                <span class="menu-item-label">License choices
                </span>
              </a>
            </li>
          </ul>
          <p class="menu-label">Tools
          </p>
          <ul class="menu-list">
            <li>
              <a href="/api-doc" class="has-icon">
                <span class="icon">
                  <i class="fas fa-database">
                  </i>
                </span>
                <span class="menu-item-label">API
                </span>
              </a>
            </li>
            <li>
              <a href="/admin" class="has-icon">
                <span class="icon">
                  <i class="fas fa-cogs">
                  </i>
                </span>
                <span class="menu-item-label">Django Admin
                </span>
              </a>
            </li>
            <li>
              <a href="{% url 'cube:about' %}" class="has-icon">
                <span class="icon">
                  <i class="far fa-question-circle">
                  </i>
                </span>
                <span class="menu-item-label">About
                </span>
              </a>
            </li>
          </ul>
        </div>
      </aside>
      <section class="section is-title-bar">
        <div class="level">
          <div class="level-left">
            <div class="level-item">
              {% block breadcrumbs %}
              {% endblock %}
            </div>
          </div>
          <div class="level-right">
            <div class="level-item">
              {% block actions %}
              {% endblock %}
            </div>
          </div>
        </div>
      </section>
      <section class="hero is-hero-bar is-small">
        <div class="hero-body">
          <div class="level">
            <div class="level-left">
              <div class="level-item">
                {% block herozone %}
                {% endblock %}
              </div>
            </div>
            <div class="level-right">
              <div class="level-item">
                {% block infoitem %}
                {% endblock %}
              </div>
            </div>
          </div>
        </div>
      </section>
      <section class="section is-main-section content">
        {% block content %}
        {% endblock %}
      </section>
      <footer class="footer">
        <div class="container-fluid">
          <div class="level">
            <div class="level-left">
              <div class="level-item">
                © 2021, Hermine project contributors
              </div>
              <div class="level-item">
                <a href="https://gitlab.com/hermine-project/hermine" style="height: 20px">
                  <img src="https://user-content.gitlab-static.net/994540c19b90ea166003d560ed33d3d0a7db35d3/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f4c6963656e73652d4147504c5f76332d626c75652e737667">
                </a>
              </div>
            </div>
            <div class="level-right">
              <div class="level-item">
                {% load version %}
                <span class='version'>{% version_date %}</span>
              </div>
              <div class="level-item">
                <div class="logo">
                  <a href="https://hermine-foss.org">
                    <img src="{% static 'cube/media/LogoHermine.svg' %}" alt="Hermine project Logo">
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div>
    <script type="text/javascript" src="{% static 'cube/js/main.js' %}">
    </script>
  </body>
</html>